source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

def shared_pods
    pod 'AFNetworking', '~> 2.0'
    pod 'JSQSystemSoundPlayer', '~>2.0.1'
    pod 'Reachability'
end
 
target 'BayunRC-Sandbox' do
    shared_pods
end
 
target 'BayunRC-Production' do
    shared_pods
end
