source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks! :linkage => :static

target 'BayunS3' do

#pod 'AWSCore'
#pod 'AWSCognito’
#pod 'AWSCognitoIdentityProvider'
 pod 'AWSMobileClient' #, :modular_headers => true
 pod 'AWSIoT'
 pod 'AWSS3'
pod 'Reachability'

end
